### ISSUE TITLE
Can't set POLLING_INTERVAL using docker-compose

### ISSUE THREAD

**Issue by bossanova808** [otherguy/docker-dropbox#32]
https://github.com/otherguy/docker-dropbox/blob/9759ba81b6bc873b2ab667dc1f2dc69a4ffc4e31/docker-entrypoint.sh#L34

Docker version 20.10.7, build f0df350
docker-compose version 1.29.2, build 5becea4c
Dropbox version 127.4.4265 (in container)

I think there's something off with this line when used with docker-compose at least...

This is my docker-compose.yml:

```yaml
    # https://github.com/otherguy/docker-dropbox
    dropbox:
        container_name: dropbox
        image: otherguy/dropbox:latest
        restart: unless-stopped
        # Host network mode for LAN sync
        network_mode: host
        # Skip permissions speeds up startup and is not needed as we pass UID/GID
        environment:
            - DROPBOX_UID=${UID}
            - DROPBOX_GID=${GUID}
            - POLLING_INTERVAL=20
            - SKIP_SET_PERMISSIONS=true
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro  
            - ${DROPBOX_CONFIG}:/opt/dropbox/.dropbox:rw
            - ${DROPBOX_FOLDER}:/opt/dropbox/Dropbox:rw   
```

I have tried all of:
- Using using a variable defined in my `'.env` (`${DROPBOX_POLLING_INTERVAL}`)
- The literal `20` as above
- The literal in string form `"20"`

... in my `docker-compose.yml` and in every case I get this in my logs:

`POLLING_INTERVAL not set to a valid number, defaulting to 5!`

I'd really like to set this to a higher value as it causes a little CPU spike every 5 seconds otherwise, which is overkill for my dropbox needs.

Thanks for any help!
