### ISSUE TITLE
[BUG] v1.10.0 docker container broken?

### ISSUE THREAD

**Issue by lolouk44** [otherguy/docker-dropbox#37]
**Describe the bug**
The container keeps restarting.

**Versions:**
 - Docker (`docker --version`):
 20.10.8, build 3967b7b
 - Docker Compose (_if used_) (`docker-compose --version`):
 1.27.4, build 4052192
 - Image Name: (`docker inspect --format='{{.Config.Image}}' [container name]`)
 otherguy/dropbox:latest
 - Image ID: (`docker inspect --format='{{.Image}}' [container name]`)
 sha256:19b642c36f22217d6e719c0960b37bdda057b5efe155191f36d7d66197431226
 - Labels: (`docker inspect --format='{{json .Config.Labels}}' [container name]`)
 bash: {"com.docker.compose.config-hash":"a51ca3fada082bc4b3d0444a0a0308a1910e1b20831b356954709a35d6044e65","com.docker.compose.container-number":"1","com.docker.compose.oneoff":"False","com.docker.compose.project":"nas","com.docker.compose.project.config_files":"docker-compose.yml","com.docker.compose.project.working_dir":"/NAS","com.docker.compose.service":"dropbox","com.docker.compose.version":"1.27.4","maintainer":"Alexander: File name too long

**Run Command:**
How did you start the container? If you use `docker-compose`, also add your compose file here.
docker-compose:
```
    dropbox:
      image: otherguy/dropbox:latest
      container_name: dropbox
      volumes:
        - /home/cctv/dropbox/contents:/opt/dropbox/Dropbox
        - /home/cctv/dropbox/settings:/opt/dropbox/.dropbox
      restart: unless-stopped
```

**Screenshots**

**Additional context**
I get this in my portainer logs:
```
,
goroutine 0 [idle]:,
runtime: unknown pc 0x7f3ecc8fb603,
stack: frame={sp:0x7fff8f6cdba0, fp:0x0} stack=[0x7fff8eecf050,0x7fff8f6ce090),
00007fff8f6cdaa0:  000000000000000a  00007f3ecc978777 ,
00007fff8f6cdab0:  00000000ffffffff  00007f3ecca7a703 ,
00007fff8f6cdac0:  00007f3ecca7c720  000000000000002e ,
00007fff8f6cdad0:  0000000000000000  0000000000000130 ,
00007fff8f6cdae0:  000000000000037f  00007f3ecca8e510 ,
00007fff8f6cdaf0:  0000000000000013  0002ffff00001fa0 ,
00007fff8f6cdb00:  0000000000000000  0000000000000000 ,
00007fff8f6cdb10:  0000000000000000  0000000000000000 ,
00007fff8f6cdb20:  0000000000000000  0000000000000000 ,
00007fff8f6cdb30:  0000000000000000  0000000000000000 ,
00007fff8f6cdb40:  0000000000000000  0000000000000000 ,
00007fff8f6cdb50:  0000000000000000  0000000000000000 ,
00007fff8f6cdb60:  0000000000000000  0000000000000000 ,
00007fff8f6cdb70:  0000000000000000  0000000000000000 ,
00007fff8f6cdb80:  00000000000000ff  0000000000000000 ,
00007fff8f6cdb90:  2525252525252525  00007f3ecc8fb5f5 ,
00007fff8f6cdba0: <00000000ff000000  0000000000000006 ,
00007fff8f6cdbb0:  000000000057e0cf  00007f3ecc8a7466 ,
00007fff8f6cdbc0:  00007fff8f6cde00  00007f3ecc88d7b7 ,
00007fff8f6cdbd0:  0000000000000020  0000000000000000 ,
00007fff8f6cdbe0:  0000000000000000  0000000000000000 ,
00007fff8f6cdbf0:  0000000000000000  0000000000000000 ,
00007fff8f6cdc00:  0000000000000000  0000000000000000 ,
00007fff8f6cdc10:  0000000000000000  0000000000000000 ,
00007fff8f6cdc20:  0000000000000000  0000000000000000 ,
00007fff8f6cdc30:  0000000000000000  0000000000000000 ,
00007fff8f6cdc40:  0000000000000000  0000000000000000 ,
00007fff8f6cdc50:  0000000000000000  0000000000000000 ,
00007fff8f6cdc60:  0000000000000000  0000000000000000 ,
00007fff8f6cdc70:  0000000000000000  0000000000000000 ,
00007fff8f6cdc80:  00007fff006f6d2e  000000000000000a ,
00007fff8f6cdc90:  00007f3ecca7a680  000000000000000a ,
runtime: unknown pc 0x7f3ecc8fb603,
stack: frame={sp:0x7fff8f6cdba0, fp:0x0} stack=[0x7fff8eecf050,0x7fff8f6ce090),
00007fff8f6cdaa0:  000000000000000a  00007f3ecc978777 ,
00007fff8f6cdab0:  00000000ffffffff  00007f3ecca7a703 ,
00007fff8f6cdac0:  00007f3ecca7c720  000000000000002e ,
00007fff8f6cdad0:  0000000000000000  0000000000000130 ,
00007fff8f6cdae0:  000000000000037f  00007f3ecca8e510 ,
00007fff8f6cdaf0:  0000000000000013  0002ffff00001fa0 ,
00007fff8f6cdb00:  0000000000000000  0000000000000000 ,
00007fff8f6cdb10:  0000000000000000  0000000000000000 ,
00007fff8f6cdb20:  0000000000000000  0000000000000000 ,
00007fff8f6cdb30:  0000000000000000  0000000000000000 ,
00007fff8f6cdb40:  0000000000000000  0000000000000000 ,
00007fff8f6cdb50:  0000000000000000  0000000000000000 ,
00007fff8f6cdb60:  0000000000000000  0000000000000000 ,
00007fff8f6cdb70:  0000000000000000  0000000000000000 ,
00007fff8f6cdb80:  00000000000000ff  0000000000000000 ,
00007fff8f6cdb90:  2525252525252525  00007f3ecc8fb5f5 ,
00007fff8f6cdba0: <00000000ff000000  0000000000000006 ,
00007fff8f6cdbb0:  000000000057e0cf  00007f3ecc8a7466 ,
00007fff8f6cdbc0:  00007fff8f6cde00  00007f3ecc88d7b7 ,
00007fff8f6cdbd0:  0000000000000020  0000000000000000 ,
00007fff8f6cdbe0:  0000000000000000  0000000000000000 ,
00007fff8f6cdbf0:  0000000000000000  0000000000000000 ,
00007fff8f6cdc00:  0000000000000000  0000000000000000 ,
00007fff8f6cdc10:  0000000000000000  0000000000000000 ,
00007fff8f6cdc20:  0000000000000000  0000000000000000 ,
00007fff8f6cdc30:  0000000000000000  0000000000000000 ,
00007fff8f6cdc40:  0000000000000000  0000000000000000 ,
00007fff8f6cdc50:  0000000000000000  0000000000000000 ,
00007fff8f6cdc60:  0000000000000000  0000000000000000 ,
00007fff8f6cdc70:  0000000000000000  0000000000000000 ,
00007fff8f6cdc80:  00007fff006f6d2e  000000000000000a ,
00007fff8f6cdc90:  00007f3ecca7a680  000000000000000a ,
,
goroutine 1 [running]:,
runtime.systemstack_switch(),
	runtime/asm_amd64.s:330 fp=0xc00002c788 sp=0xc00002c780 pc=0x466220,
runtime.main(),
	runtime/proc.go:134 +0x70 fp=0xc00002c7e0 sp=0xc00002c788 pc=0x438410,
runtime.goexit(),
	runtime/asm_amd64.s:1374 +0x1 fp=0xc00002c7e8 sp=0xc00002c7e0 pc=0x468001,
,
rax    0x0,
rbx    0x7f3ecc85e740,
rcx    0x7f3ecc8fb603,
rdx    0x6,
rdi    0x2e,
rsi    0x2e,
rbp    0x2e,
rsp    0x7fff8f6cdba0,
r8     0x7fff8f6cdbd0,
r9     0x0,
r10    0x8,
r11    0x206,
r12    0x6,
r13    0x7fff8f6cdec0,
r14    0x573398,
r15    0x0,
rip    0x7f3ecc8fb603,
rflags 0x206,
cs     0x33,
fs     0x0,
gs     0x0
```

**Comment by lolouk44** [comment]
in addition, I've reverted to 1.0.9 and the container doesn't restart...

**Comment by reverendj1** [comment]
I had the same issue and the same log on a new install. I had to switch to 1.9.0 and turn on DROPBOX_SKIP_UPDATE to get it working.

**Comment by mneimeyer** [comment]
I'm also getting the same log/error but the DROPBOX_SKIP_UPDATE isn't helping me unless I've implemented that wrong.

**Comment by reverendj1** [comment]
@mneimeyer you may have to stop the container and do a `docker system prune --all --force --volumes` first to clear out all your old containers. Be warned, this deletes all stopped containers, their non-persistent volumes, and your image cache.

Here is my working docker-compose.yml

```yaml
version: "2"
# Need to run on host on new install to be able to watch all files:
# echo fs.inotify.max_user_watches=100000 | sudo tee -a /etc/sysctl.conf; sudo sysctl -p
services:
  dropbox:
    image: otherguy/dropbox:1.9.0
    container_name: dropbox
    environment:
      - TZ=America/Detroit
      - DROPBOX_UID=1000
      - DROPBOX_GID=1000
      # Can't update Dropbox client or Docker image until this bug is fixed. https://github.com/otherguy/docker-dropbox/issues/37
      - DROPBOX_SKIP_UPDATE=true
    volumes:
      - ./config:/opt/dropbox/.dropbox
      - /data:/opt/dropbox/Dropbox
    restart: unless-stopped
```
