### ISSUE TITLE
[BUG] Error when connecting a new account

### ISSUE THREAD

**Issue by samuelvaneck** [otherguy/docker-dropbox#38]
**Describe the bug**
When connecting a new account to the Dropbox with the docker container I get an error:

```
Dropbox needs to rename your existing folder or file named Dropbox to finish installing. Please close any open documents and try again.
```

I was able to get arround the issue by not updating Dropbox as startup using the DROPBOX_SKIP_UPDATE environment variable. 

**Versions:**
 - Docker version`; 20.10.8 
 - Docker Compose: v2.0.0
 - Image Name: otherguy/dropbox:1.9.0

**Run Command:**
Run the container with a docker-compose up:
```
version: "2.1"
services:
  dropbox:
    image: otherguy/dropbox:1.9.0
    container_name: dropbox
    environment:
      TZ: 'Europe/Amsterdam'
      DROPBOX_GID: 1004
      DROPBOX_UID: 1000
    volumes:
      - '/etc/timezone:/etc/timezone'
      - '/etc/localtime:/etc/localtime'
      - '/Users/user/Dropbox:/opt/dropbox/Dropbox'
      - './settings:/opt/dropbox/.dropbox'
    restart: always
    mem_limit: 4G
```

**Additional context**
