### ISSUE TITLE
[BUG] Does not start with updated version (125.4.3474->143.4.4161)

### ISSUE THREAD

**Issue by adradr** [otherguy/docker-dropbox#51]
**Describe the bug**
After updating dropbox inside the container it does not want to start up. I guess its not particularly the bug of this dockerized version, but probably somebody has faced this issuee already. I have been using the previous version fine, but after 20 days it warned me to update and it also wasn't working anymore. 

Current version: Dropbox daemon version: 143.4.4161
Previous working version: Dropbox daemon version: 125.4.3474

I am using a `Linux machine 4.15.0-169-generic #177-Ubuntu SMP Thu Feb 3 10:50:38 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux` with `Docker version 19.03.12, build 48a66213fe`

**Run Command:**
```
---
version: "2.1"
services:
  dropbox:
    image: otherguy/dropbox:latest
    container_name: dropbox
    network_mode: host
    environment:
      - TZ=Europe/Budapest
      - DROPBOX_UID=1000
      - DROPBOX_GID=1000
      - POLLING_INTERVAL=15
      - DROPBOX_SKIP_UPDATE=false
    volumes:
      - /home/adr/dropbox-docker/dropbox_config:/opt/dropbox/.dropbox
      - /home/adr/dropbox-docker/dropbox_files:/opt/dropbox/Dropbox
    restart: unless-stopped
```

**Additional context**

**Before updating**
```
...
You're using an old version of Dropbox. Please update within the next 6 days to continue using Dropbox.

https://www.dropbox.com/downloading?from_client=True
Up to date
Up to date
Up to date
Up to date
...
```

**After updating**
```
root@ machine:/opt/dropbox/Dropbox# dropbox status
Starting...
root@ machine:/opt/dropbox/Dropbox# dropbox status
Starting...
root@ machine:/opt/dropbox/Dropbox# dropbox status
Starting...
root@ machine:/opt/dropbox/Dropbox# dropbox status
Starting...
root@ machine:/opt/dropbox/Dropbox# dropbox status
Starting...
root@ machine:/opt/dropbox/Dropbox# dropbox status
Starting...
root@ machine:/opt/dropbox/Dropbox# dropbox version
Dropbox daemon version: 143.4.4161
Dropbox command-line interface version: 2020.03.04
```
