### ISSUE TITLE
[BUG] "Dropbox isn't running!" when restarting container - QNAP Container Station instance

### ISSUE THREAD

**Issue by nickdiacre** [otherguy/docker-dropbox#61]
**Describe the bug**
"Dropbox isn't running!" message is appearing in the console when I restart teh container

**Versions:**
 - Docker version 20.10.17-qnap1, build 0474f29
 - docker-compose version 1.29.2, build 1ca12643
 - Image Name: otherguy/dropbox:latest
 - Image ID: sha256:19b642c36f22217d6e719c0960b37bdda057b5efe155191f36d7d66197431226
 - Labels:
```
{
  "com.docker.compose.config-hash": "5342602b60924c608f7ef093dbb5a98215386182c7557a15e141a3ef3cc53e84",
  "com.docker.compose.container-number": "1",
  "com.docker.compose.oneoff": "False",
  "com.docker.compose.project": "dropbox",
  "com.docker.compose.project.config_files": "docker-compose.yml",
  "com.docker.compose.project.working_dir": "/share/ZFS19_DATA/Container/container-station-data/application/dropbox",
  "com.docker.compose.service": "dropbox",
  "com.docker.compose.version": "1.29.2",
  "maintainer": "Alexander Graf <alex@otherguy.io>",
  "org.label-schema.build-date": "2021-09-17T00:13:41+02:00",
  "org.label-schema.description": "Standalone Dropbox client",
  "org.label-schema.name": "Dropbox",
  "org.label-schema.schema-version": "1.0",
  "org.label-schema.vcs-ref": "1f0d1c6",
  "org.label-schema.vcs-url": "https://github.com/otherguy/docker-dropbox",
  "org.label-schema.version": "1.10.0"
}

```
**Run Command:**
```
version: '3.3'

services:
    dropbox:
        restart: always
        container_name: dropbox
        network_mode: host
        environment:
            - TZ=Europe/London
            - 'DROPBOX_UID=0'
            - 'DROPBOX_GID=0'
            - POLLING_INTERVAL=20
        volumes:
            - '/share/DB_Store/settings:/opt/dropbox/.dropbox'
            - '/share/DB_Store/Dropbox:/opt/dropbox/Dropbox (Giggle)'
        image: 'otherguy/dropbox:latest'
```

**Screenshots**
![image](https://user-images.githubusercontent.com/5656214/192324631-8345b352-d449-470c-a53a-41a6e5b463ce.png)

**Additional context**
My DB just about finished syncing, and now says "Dropbox isn't running!", I have tried restarting the container to no avail, is there something obvious I am missing here? Apologies if it is.

Many thanks

Nick
